#!/usr/bin/env bash
NEONBOOK_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NEONBOOK_SCRIPTS_DIR="$NEONBOOK_ROOT_DIR/scripts"
NEONBOOK_LOGGING_LIB_SCRIPT="$NEONBOOK_SCRIPTS_DIR/lib/logging.sh"

NEONBOOK_AI_PLANS_DIR="$NEONBOOK_ROOT_DIR/../../ai-plans"

NEONBOOK_SPHINX_BOOK_DIR="$NEONBOOK_ROOT_DIR"
NEONBOOK_SPHINX_VENV_DIR="$NEONBOOK_SPHINX_BOOK_DIR/.venv"
NEONBOOK_SPHINX_BUILD_DIR="$NEONBOOK_ROOT_DIR/build/book"

NEONBOOK_SPHINX_BENCHMARK_SOURCE_DIR="$NEONBOOK_ROOT_DIR/../../benchmark"

NEONBOOK_SPHINX_BENCHMARK_TARGET_DIR="$NEONBOOK_SPHINX_BOOK_DIR/source/benchmarks"
NEONBOOK_SPHINX_BENCHMARK_INDEX="$NEONBOOK_SPHINX_BENCHMARK_TARGET_DIR/index.md"

NEONBOOK_SPHINX_PLANS_SOURCE_DIR="$NEONBOOK_AI_PLANS_DIR"
NEONBOOK_SPHINX_AI_TARGET_DIR="$NEONBOOK_SPHINX_BOOK_DIR/source/ai-conversations"
NEONBOOK_SPHINX_AI_INDEX="$NEONBOOK_SPHINX_AI_TARGET_DIR/index.md"

NEONBOOK_SPHINX_DYNAMICS_SCRIPT="$NEONBOOK_SCRIPTS_DIR/sphinx/dynamics.sh"
